app/urls.py
from django.urls import path
from app.views import organizer, event, deck

from django.views.generic import TemplateView


class Index(TemplateView):
    template_name = 'index.html'


app_name = 'app'

urlpatterns = [
    path('', Index.as_view(), name='index',),
    path(
        'organizer/create/',
        organizer.Create.as_view(),
        name='organizer_create',
    ),
    path(
        'organizer/list/',
        organizer.List.as_view(),
        name='organizer_list',
    ),
    path(
        'organizer/<int:pk>/detail/',
        organizer.Detail.as_view(),
        name='organizer_detail',
    ),
    path(
        'organizer/<int:pk>/update/',
        organizer.Update.as_view(),
        name='organizer_update',
    ),
    path(
        'organizer/<int:pk>/delete/',
        organizer.Delete.as_view(),
        name='organizer_delete',
    ),
    path(
        'event/create/',
        event.Create.as_view(),
        name='event_create',
    ),
    path(
        'event/list/',
        event.List.as_view(),
        name='event_list',
    ),
    path(
        'event/<uuid:pk>/detail/',
        event.Detail.as_view(),
        name='event_detail',
    ),
    path(
        'event/<uuid:pk>/update/',
        event.Update.as_view(),
        name='event_update',
    ),
    path(
        'event/<uuid:pk>/delete/',
        event.Delete.as_view(),
        name='event_delete',
    ),
    path(
        'event/<uuid:event_uuid>/deck/create/',
        deck.Create.as_view(),
        name='deck_create',
    ),
    path(
        'event/<uuid:event_uuid>/deck/list/',
        deck.List.as_view(),
        name='deck_list',
    ),
    path(
        'event/<uuid:event_uuid>/deck/<uuid:pk>/detail/',
        deck.Detail.as_view(),
        name='deck_detail',
    ),
    path(
        'event/<uuid:event_uuid>/deck/<uuid:pk>/update/',
        deck.Update.as_view(),
        name='deck_update',
    ),
    path(
        'event/<uuid:event_uuid>/deck/<uuid:pk>/delete/',
        deck.Delete.as_view(),
        name='deck_delete',
    ),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('', include('django.contrib.auth.urls')),
]

urlpatterns += static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)

urlpatterns += static(
    settings.STATIC_URL,
    document_root=settings.STATIC_ROOT
)

app/models/organizer.py
from django.contrib.auth.models import AbstractUser


class Organizer(AbstractUser):
    pass

app/forms/organizer.py
from app.models import Organizer
from django import forms
from django.contrib.auth.forms import UserChangeForm, UserCreationForm


class CreateForm(UserCreationForm):
    class Meta:
        model = Organizer
        fields = ('username', 'password1', 'password2',)
        labels = {
            'username': 'ハンドルネーム(必須)',
        }
        widgets = {
            'username': forms.TextInput(
                attrs={
                    'placeholder': 'ルゥ@Rue1DM',
                },
            ),
        }


class UpdateForm(UserChangeForm):
    password = None

    class Meta:
        model = Organizer
        fields = ('username',)
        labels = {
            'username': 'ハンドルネーム(必須)',
        }
        widgets = {
            'username': forms.TextInput(
                attrs={
                    'placeholder': 'ルゥ@Rue1DM',
                },
            ),
        }

app/views/organizer.py
from app.forms.organizer import CreateForm, UpdateForm
from app.mixins import MyOrganizerMixin
from app.models import Organizer
from django.contrib.auth import authenticate, login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views import generic


class Create(generic.CreateView):
    template_name = 'organizer/create.html'
    model = Organizer
    form_class = CreateForm
    success_url = reverse_lazy('app:index')

    def form_valid(self, form):
        respons = super().form_valid(form)

        un = form.cleaned_data.get('username')
        pw = form.cleaned_data.get('password1')
        user = authenticate(username=un, password=pw)
        login(self.request, user)

        return respons


class List(LoginRequiredMixin, generic.ListView):
    template_name = 'organizer/list.html'
    model = Organizer


class Detail(MyOrganizerMixin, generic.DetailView):
    template_name = 'organizer/detail.html'
    model = Organizer


class Update(MyOrganizerMixin, generic.UpdateView):
    template_name = 'organizer/update.html'
    model = Organizer
    form_class = UpdateForm
    success_url = reverse_lazy('app:organizer_list')


class Delete(MyOrganizerMixin, generic.DeleteView):
    template_name = 'organizer/delete.html'
    model = Organizer
    success_url = reverse_lazy('app:organizer_list')

app/templates/organizer/create.html
{% extends 'base.html' %}

{% block contents %}
<h2>主催者登録</h2>

<form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" value="登録する" class="btn btn-primary mx-auto d-block">
</form>
{% endblock %}

app/templates/organizer/delete.html
{% extends 'base.html' %}

{% block contents %}
<form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="削除する">
</form>
{% endblock %}

app/templates/organizer/detail.html
{% extends 'base.html' %}

{% block contents %}
<h2>{{ organizer.username }}さんの詳細</h2>

<table class="table table-striped">
    <tr>
        <th>主催者ID</th>
        <td>{{ organizer.id }}</td>
    </tr>
    <tr>
        <th>ハンドルネーム</th>
        <td>{{ organizer.username }}</td>
    </tr>
    <tr>
        <th>登録日時</th>
        <td>
            {{ organizer.date_joined | date }}<br>
            {{ organizer.date_joined | time }}
        </td>
    </tr>
</table>

<p>
    <a href="{% url 'app:organizer_update' organizer.pk %}">更新</a> /
    <a href="{% url 'app:organizer_delete' organizer.pk %}">削除</a>
</p>

<p>
    <a href="{% url 'logout' %}">ログアウトする</a>
</p>
{% endblock %}

app/templates/organizer/list.html
{% extends 'base.html' %}

{% block contents %}
<h2>主催者リスト</h2>

<table class="table table-striped">
    <tr>
        <th>ID</th>
        <th>主催者名</th>
    </tr>
    {% for organizer in organizer_list %}
    <tr>
        <td>{{ organizer.id }}</td>
        <td>
            <a href="{% url 'app:organizer_detail' organizer.pk %}">
                {{ organizer.username }}
            </a>
        </td>
    </tr>
    {% endfor %}
</table>
{% endblock %}

app/templates/organizer/update.html
{% extends 'base.html' %}

{% block contents %}
<form action="" method="POST">
    {% csrf_token %}
    <table class="table table-striped">
        {{form.as_table}}
    </table>
    <input type="submit" value="更新する">
</form>
{% endblock %}