app/urls.py
from django.urls import path
from app.views import organizer, event, deck

from django.views.generic import TemplateView


class Index(TemplateView):
    template_name = 'index.html'


app_name = 'app'

urlpatterns = [
    path('', Index.as_view(), name='index',),
    path(
        'organizer/create/',
        organizer.Create.as_view(),
        name='organizer_create',
    ),
    path(
        'organizer/list/',
        organizer.List.as_view(),
        name='organizer_list',
    ),
    path(
        'organizer/<int:pk>/detail/',
        organizer.Detail.as_view(),
        name='organizer_detail',
    ),
    path(
        'organizer/<int:pk>/update/',
        organizer.Update.as_view(),
        name='organizer_update',
    ),
    path(
        'organizer/<int:pk>/delete/',
        organizer.Delete.as_view(),
        name='organizer_delete',
    ),
    path(
        'event/create/',
        event.Create.as_view(),
        name='event_create',
    ),
    path(
        'event/list/',
        event.List.as_view(),
        name='event_list',
    ),
    path(
        'event/<uuid:pk>/detail/',
        event.Detail.as_view(),
        name='event_detail',
    ),
    path(
        'event/<uuid:pk>/update/',
        event.Update.as_view(),
        name='event_update',
    ),
    path(
        'event/<uuid:pk>/delete/',
        event.Delete.as_view(),
        name='event_delete',
    ),
    path(
        'event/<uuid:event_uuid>/deck/create/',
        deck.Create.as_view(),
        name='deck_create',
    ),
    path(
        'event/<uuid:event_uuid>/deck/list/',
        deck.List.as_view(),
        name='deck_list',
    ),
    path(
        'event/<uuid:event_uuid>/deck/<uuid:pk>/detail/',
        deck.Detail.as_view(),
        name='deck_detail',
    ),
    path(
        'event/<uuid:event_uuid>/deck/<uuid:pk>/update/',
        deck.Update.as_view(),
        name='deck_update',
    ),
    path(
        'event/<uuid:event_uuid>/deck/<uuid:pk>/delete/',
        deck.Delete.as_view(),
        name='deck_delete',
    ),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('', include('django.contrib.auth.urls')),
]

urlpatterns += static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)

urlpatterns += static(
    settings.STATIC_URL,
    document_root=settings.STATIC_ROOT
)

app/models/event.py
from datetime import date
from uuid import uuid4

from app.models import Organizer
from django.db import models
from django.db.models.deletion import CASCADE


class Event(models.Model):
    uuid = models.UUIDField(
        primary_key=True,
        default=uuid4,
        verbose_name='イベントID',
    )

    organizer = models.ForeignKey(
        Organizer,
        on_delete=CASCADE,
        verbose_name='主催者',
    )

    title = models.CharField(
        max_length=128,
        verbose_name='イベント名',
    )

    date = models.DateField(
        default=date.today,
        verbose_name='開催日',
    )

    message = models.TextField(
        max_length=1024,
        null=True,
        blank=True,
        default='デッキ登録には\n・参加表明の番号\n・ハンドルネーム\n・デッキ画像\nの3つが必要です。',
        verbose_name='参加者へのメッセージ',
    )

    is_active = models.BooleanField(
        default=True,
        choices=(
            (True, '受付中'),
            (False, '受付終了'),
        ),
        verbose_name='状態',
    )

    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name='作成日時',
    )

    updated_at = models.DateTimeField(
        auto_now=True,
        verbose_name='更新日時',
    )

    def __str__(self):
        return f"{self.title}"

app/forms/event.py
from app.models import Event
from django import forms


class CreateForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = ('title', 'date', 'message', 'is_active', )
        labels = {
            'title': 'イベント名(必須)',
            'date': '開催日(必須)',
            'message': '参加者へのメッセージ(任意)',
            'is_active': '状態',
        }
        widgets = {
            'title': forms.TextInput(
                attrs={
                    'placeholder': '第1回 DM秋田CS【アドバンス】',
                },
            ),
            'date': forms.DateInput(
                attrs={
                    'type': 'date',
                },
            ),
        }


class UpdateForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = ('is_active', )
        labels = {
            'is_active': '状態',
        }

app/views/event.py
from app.forms.event import CreateForm, UpdateForm
from app.mixins import MyEventMixin
from app.models import Event
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views import generic
import shutil
from django.conf import settings


class Create(LoginRequiredMixin, generic.CreateView):
    template_name = 'event/create.html'
    model = Event
    success_url = reverse_lazy('app:event_list')
    form_class = CreateForm

    def form_valid(self, form):
        form.instance.organizer = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        kw = {'pk': self.object.pk, }
        return reverse_lazy('app:event_detail', kwargs=kw)


class List(LoginRequiredMixin, generic.ListView):
    template_name = 'event/list.html'
    model = Event

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(organizer=self.request.user)
        queryset = queryset.order_by('date')
        queryset = queryset.reverse()
        return queryset


class Detail(MyEventMixin, generic.DetailView):
    template_name = 'event/detail.html'
    model = Event


class Update(MyEventMixin, generic.UpdateView):
    template_name = 'event/update.html'
    model = Event
    form_class = UpdateForm

    def get_success_url(self):
        kw = {'pk': self.object.pk, }
        return reverse_lazy('app:event_detail', kwargs=kw)


class Delete(MyEventMixin, generic.DeleteView):
    template_name = 'event/delete.html'
    model = Event
    success_url = reverse_lazy('app:event_list')


class DonwloadAllDeck(MyEventMixin, generic.RedirectView):
    def get(self, request, *args, **kwargs):
        event_uuid = self.kwargs['pk']
        shutil.make_archive('./zips/files', 'zip', f"{settings.MEDIA_ROOT}/")
        return super().get(request, *args, **kwargs)

app/templates/event/create.html
{% extends 'base.html' %}

{% block contents %}
<h2>マイイベント作成</h2>

<form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" value="作成する" class="btn btn-primary mx-auto d-block">
</form>
{% endblock %}

app/templates/event/delete.html
{% extends 'base.html' %}

{% block contents %}
<h2>イベントの削除</h2>

<p>{{ event.date }}の『{{ event.title }}』を削除しますか？</p>

<form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="削除する">
</form>
{% endblock %}

app/templates/event/detail.html
{% extends 'base.html' %}

{% block contents %}
<h2>イベント詳細</h2>

<table class="table table-striped">
    <tr>
        <th>イベント名</th>
        <td>{{ event.title }}</td>
    </tr>
    <tr>
        <th>開催日</th>
        <td>{{ event.date }}</td>
    </tr>
    <tr>
        <th>主催者</th>
        <td>{{ event.organizer.username }}</td>
    </tr>
    <tr>
        <th>参加者へのメッセージ</th>
        <td>
            <p>{{ event.message | linebreaksbr }}</p>
        </td>
    </tr>
    <tr>
        <th>状態</th>
        <td>{{ event.get_is_active_display }}</td>
    </tr>
</table>

<p>
    <a href="{% url 'app:event_update' event.pk %}">更新</a> /
    <a href="{% url 'app:event_delete' event.pk %}">削除</a>
</p>

<p>
    <a href="{% url 'app:deck_create' event.pk %}">デッキリスト登録</a> /
    <a href="{% url 'app:deck_list' event.pk %}">デッキリスト閲覧</a>
</p>
{% endblock %}

app/templates/event/list.html
{% extends 'base.html' %}

{% block contents %}

<h2>受付中のイベント</h2>
<table class="table table-striped">
    <tr>
        <th>開催日</th>
        <th>イベント名</th>
    </tr>
    {% for event in event_list %}
    {% if event.is_active %}
    <tr>
        <td>{{ event.date }}</td>
        <td>
            <a href="{% url 'app:event_detail' event.pk %}">
                {{ event.title }}
            </a>
        </td>
    </tr>
    {% endif %}
    {% endfor %}
</table>

<h2>終了したイベント</h2>
<table class="table table-striped">
    <tr>
        <th>開催日</th>
        <th>イベント名</th>
    </tr>
    {% for event in event_list %}
    {% if not event.is_active %}
    <tr>
        <td>{{ event.date }}</td>
        <td>
            <a href="{% url 'app:event_detail' event.pk %}">
                {{ event.title }}
            </a>
        </td>
    </tr>
    {% endif %}
    {% endfor %}
</table>

{% endblock %}

app/templates/event/update.html
{% extends 'base.html' %}

{% block contents %}
<form action="" method="POST">
    {% csrf_token %}
    <table class="table table-striped">
        {{form.as_table}}
    </table>
    <input type="submit" value="更新する">
</form>
{% endblock %}