app/urls.py
from django.urls import path
from app.views import organizer, event, deck

from django.views.generic import TemplateView


class Index(TemplateView):
    template_name = 'index.html'


app_name = 'app'

urlpatterns = [
    path('', Index.as_view(), name='index',),
    path(
        'organizer/create/',
        organizer.Create.as_view(),
        name='organizer_create',
    ),
    path(
        'organizer/list/',
        organizer.List.as_view(),
        name='organizer_list',
    ),
    path(
        'organizer/<int:pk>/detail/',
        organizer.Detail.as_view(),
        name='organizer_detail',
    ),
    path(
        'organizer/<int:pk>/update/',
        organizer.Update.as_view(),
        name='organizer_update',
    ),
    path(
        'organizer/<int:pk>/delete/',
        organizer.Delete.as_view(),
        name='organizer_delete',
    ),
    path(
        'event/create/',
        event.Create.as_view(),
        name='event_create',
    ),
    path(
        'event/list/',
        event.List.as_view(),
        name='event_list',
    ),
    path(
        'event/<uuid:pk>/detail/',
        event.Detail.as_view(),
        name='event_detail',
    ),
    path(
        'event/<uuid:pk>/update/',
        event.Update.as_view(),
        name='event_update',
    ),
    path(
        'event/<uuid:pk>/delete/',
        event.Delete.as_view(),
        name='event_delete',
    ),
    path(
        'event/<uuid:event_uuid>/deck/create/',
        deck.Create.as_view(),
        name='deck_create',
    ),
    path(
        'event/<uuid:event_uuid>/deck/list/',
        deck.List.as_view(),
        name='deck_list',
    ),
    path(
        'event/<uuid:event_uuid>/deck/<uuid:pk>/detail/',
        deck.Detail.as_view(),
        name='deck_detail',
    ),
    path(
        'event/<uuid:event_uuid>/deck/<uuid:pk>/update/',
        deck.Update.as_view(),
        name='deck_update',
    ),
    path(
        'event/<uuid:event_uuid>/deck/<uuid:pk>/delete/',
        deck.Delete.as_view(),
        name='deck_delete',
    ),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('', include('django.contrib.auth.urls')),
]

urlpatterns += static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)

urlpatterns += static(
    settings.STATIC_URL,
    document_root=settings.STATIC_ROOT
)

app/models/deck.py
import os
from uuid import uuid4

from app.models import Event
from django.db import models
from django.db.models.deletion import CASCADE


def _image_upload_to(instance, filename):
    uuid = uuid4()
    (_, ext) = os.path.splitext(filename)
    new_name = f"{instance.number}_{instance.name}_{uuid}{ext}"
    return f"{instance.event.uuid}/{new_name}"


class Deck(models.Model):
    uuid = models.UUIDField(
        primary_key=True,
        default=uuid4,
        verbose_name='デッキID',
    )

    event = models.ForeignKey(
        Event,
        on_delete=CASCADE,
        verbose_name='イベント',
    )

    number = models.IntegerField(
        verbose_name='識別番号',
    )

    name = models.CharField(
        max_length=128,
        verbose_name='ハンドルネーム',
    )

    image = models.ImageField(
        upload_to=_image_upload_to,
        verbose_name='デッキ画像',
    )

    remark = models.TextField(
        max_length=1024,
        null=True,
        blank=True,
        verbose_name='備考',
    )

    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name='作成日時',
    )

    updated_at = models.DateTimeField(
        auto_now=True,
        verbose_name='更新日時',
    )

    def __str__(self):
        return f"{self.event_id}_{self.number}-{self.name}"

app/models/event.py
from datetime import date
from uuid import uuid4

from app.models import Organizer
from django.db import models
from django.db.models.deletion import CASCADE


class Event(models.Model):
    uuid = models.UUIDField(
        primary_key=True,
        default=uuid4,
        verbose_name='イベントID',
    )

    organizer = models.ForeignKey(
        Organizer,
        on_delete=CASCADE,
        verbose_name='主催者',
    )

    title = models.CharField(
        max_length=128,
        verbose_name='イベント名',
    )

    date = models.DateField(
        default=date.today,
        verbose_name='開催日',
    )

    message = models.TextField(
        max_length=1024,
        null=True,
        blank=True,
        default='デッキ登録には\n・参加表明の番号\n・ハンドルネーム\n・デッキ画像\nの3つが必要です。',
        verbose_name='参加者へのメッセージ',
    )

    is_active = models.BooleanField(
        default=True,
        choices=(
            (True, '受付中'),
            (False, '受付終了'),
        ),
        verbose_name='状態',
    )

    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name='作成日時',
    )

    updated_at = models.DateTimeField(
        auto_now=True,
        verbose_name='更新日時',
    )

    def __str__(self):
        return f"{self.title}"

app/forms/deck.py
from app.models import Deck
from django import forms


class CreateForm(forms.ModelForm):
    class Meta:
        model = Deck
        fields = ('number', 'name', 'image', 'remark', )
        labels = {
            'number': '識別番号(必須)',
            'name': 'ハンドルネーム(必須)',
            'image': 'デッキ画像(必須)',
            'remark': '備考',
        }
        widgets = {
            'number': forms.NumberInput(
                attrs={
                    'placeholder': '1',
                },
            ),
            'name': forms.TextInput(
                attrs={
                    'placeholder': 'ルゥ@Rue1DM',
                },
            ),
            'remark': forms.Textarea(
                attrs={
                    'placeholder': '主催者からの指示があった場合に記入してください。\n',
                },
            ),
        }


class UpdateForm(forms.ModelForm):
    class Meta:
        model = Deck
        fields = ('remark', )
        labels = {
            'remark': '備考',
        }
        widgets = {
            'remark': forms.Textarea(
                attrs={
                    'placeholder': '主催者からの指示があった場合に記入してください。\n',
                },
            ),
        }

app/views/deck.py
from app.forms.deck import CreateForm, UpdateForm
from app.mixins import MyDeckMixin, MyEventMixin
from app.models import Deck, Event
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views import generic

from django.contrib import messages


class Create(generic.CreateView):
    template_name = 'deck/create.html'
    model = Deck
    form_class = CreateForm

    def post(self, request, *args, **kwargs):
        event = Event.objects.get(uuid=self.kwargs['event_uuid'])
        if not event.is_active:
            kw = {'event_uuid': self.kwargs['event_uuid'], }
            url = reverse_lazy('app:deck_create', kwargs=kw)
            return HttpResponseRedirect(url)

        return super().post(request, *args, **kwargs)

    def form_valid(self, form):
        messages.success(self.request, "デッキを登録しました。")

        event = Event.objects.get(uuid=self.kwargs['event_uuid'])

        form.instance.event = event
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        event = Event.objects.get(uuid=self.kwargs['event_uuid'])

        context = super().get_context_data(**kwargs)
        context['event'] = event
        return context

    def get_success_url(self):
        kw = {
            'event_uuid': self.kwargs['event_uuid'],
            'pk': self.object.pk,
        }
        return reverse_lazy('app:deck_detail', kwargs=kw)


class List(MyEventMixin, generic.ListView):
    template_name = 'deck/list.html'
    model = Deck

    def get_context_data(self, **kwargs):
        event = Event.objects.get(pk=self.kwargs['event_uuid'])
        context = super().get_context_data(**kwargs)
        context['event'] = event
        return context

    def get_queryset(self):
        event = Event.objects.get(pk=self.kwargs['event_uuid'])

        queryset = super().get_queryset()
        queryset = queryset.filter(event=event)
        queryset = queryset.order_by('number', 'created_at')
        return queryset


class Detail(generic.DetailView):
    template_name = 'deck/detail.html'
    model = Deck


class Update(MyDeckMixin, generic.UpdateView):
    template_name = 'deck/update.html'
    model = Deck
    form_class = UpdateForm

    def form_valid(self, form):
        messages.success(self.request, "デッキを更新しました。")
        return super().form_valid(form)

    def get_success_url(self):
        kw = {
            'event_uuid': self.kwargs['event_uuid'],
            'pk': self.object.pk,
        }
        return reverse_lazy('app:deck_detail', kwargs=kw)


class Delete(MyDeckMixin, generic.DeleteView):
    template_name = 'deck/delete.html'
    model = Deck

    def post(self, request, *args, **kwargs):
        messages.success(self.request, "デッキを削除しました。")
        return super().post(request, *args, **kwargs)

    def get_success_url(self):
        kw = {'event_uuid': self.kwargs['event_uuid'], }
        return reverse_lazy('app:deck_list', kwargs=kw)

app/templates/deck/create.html
{% extends 'base.html' %}

{% block contents %}
<h2>{{ event.title }}</h2>

<table class="table table-striped">
    <tr>
        <th>開催日</th>
        <td>{{ event.date }}</td>
    </tr>
    <tr>
        <th>主催者</th>
        <td>{{ event.organizer.username }}</td>
    </tr>
    <tr>
        <th>参加者へのメッセージ</th>
        <td>
            <p>{{ event.message | linebreaksbr }}</p>
        </td>
    </tr>
</table>

<h2>デッキ登録</h2>

{% if event.is_active %}
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form %}
    <p id="preview">選択デッキ画像：</p>
    <input type="submit" value="登録する" id="submit" class="btn btn-primary mx-auto d-block">
</form>

<script>
    document.getElementById('id_image').addEventListener(
        'change',
        function () {
            var fileReader = new FileReader();
            fileReader.onload = (
                function () {
                    let img = document.createElement('img');
                    img.src = fileReader.result;
                    img.height = 128;
                    img.class = "img-thumbnail";
                    document.getElementById('preview').append(img);
                }
            );
            fileReader.readAsDataURL(this.files[0]);

            const limit = 1024 * 1024 * 8;
            if (this.files[0].size > limit) {
                document.getElementById('submit').disabled = true;
                alert('画像が大きすぎます。(上限8MG)')
            }
        }
    );
</script>
{% else %}
<p>受付は終了しました。</p>
{% endif %}

{% endblock %}

app/templates/deck/delete.html
{% extends 'base.html' %}

{% block contents %}
<form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="削除する">
</form>
{% endblock %}

app/templates/deck/detail.html
{% extends 'base.html' %}

{% block contents %}
<h2>{{ deck.number }}「{{ deck.name }}」さん のデッキリスト</h2>

<a href="{{ deck.image.url }}">
    <img class="mw-100" src="{{ deck.image.url }}" />
</a>

<h2>詳細データ</h2>

<table class="table table-striped">
    <tr>
        <th>イベント</th>
        <td>
            {{ deck.event.date }}<br>
            {{ deck.event.title }}
        </td>
    </tr>
    <tr>
        <th>備考</th>
        <td>{{ deck.remark }}</td>
    </tr>
    <tr>
        <th>作成日時</th>
        <td>{{ deck.created_at }}</td>
    </tr>
    <tr>
        <th>更新日時</th>
        <td>{{ deck.updated_at }}</td>
    </tr>
</table>

<p>
    <a href="{% url 'app:deck_update' deck.event.uuid deck.pk %}">更新</a> /
    <a href="{% url 'app:deck_delete' deck.event.uuid deck.pk %}">削除</a>
</p>
{% endblock %}

app/templates/deck/list.html
{% extends 'base.html' %}

{% block contents %}
<h2>{{ event.title }}</h2>

<table class="table table-striped">
    <tr>
        <th>主催者</th>
        <td>{{ event.organizer.username }}</td>
    </tr>
    <tr>
        <th>開催日</th>
        <td>{{ event.date }}</td>
    </tr>
    <tr>
        <th>状態</th>
        <td>{{ event.get_is_active_display }}</td>
    </tr>
</table>

<h2>登録デッキリスト</h2>

<p>デッキ画像タップで詳細</p>

<table class="table table-striped">
    <tr>
        <th>識別番号</th>
        <th>ハンドルネーム</th>
        <th>デッキ画像</th>
        <th>日時</th>
        <th>備考</th>
    </tr>
    {% for deck in deck_list %}
    <tr>
        <td>{{ deck.number }}</td>
        <td>{{ deck.name | truncatechars:16 }}</td>
        <td>
            <p>
                <a href="{% url 'app:deck_detail' deck.event.uuid deck.pk %}">
                    <img class="mw-100" src="{{ deck.image.url }}" />
                </a>
            </p>
        </td>
        <td>
            {{ deck.updated_at | date }}<br>
            {{ deck.updated_at | time }}
        </td>
        <td>{{ deck.remark | truncatechars:8 }}</td>
    </tr>
    {% endfor %}
</table>
{% endblock %}

app/templates/deck/update.html
{% extends 'base.html' %}

{% block contents %}
<h2>deck update</h2>

<form action="" method="POST">
    {% csrf_token %}
    <table class="table table-striped">
        {{form.as_table}}
    </table>
    <input type="submit" value="更新する">
</form>
{% endblock %}