app/urls.py
from django.urls import path
from app.views import organizer, event, deck

from django.views.generic import TemplateView


class Index(TemplateView):
    template_name = 'index.html'


app_name = 'app'

urlpatterns = [
    path('', Index.as_view(), name='index',),
    path(
        'organizer/create/',
        organizer.Create.as_view(),
        name='organizer_create',
    ),
    path(
        'organizer/list/',
        organizer.List.as_view(),
        name='organizer_list',
    ),
    path(
        'organizer/<int:pk>/detail/',
        organizer.Detail.as_view(),
        name='organizer_detail',
    ),
    path(
        'organizer/<int:pk>/update/',
        organizer.Update.as_view(),
        name='organizer_update',
    ),
    path(
        'organizer/<int:pk>/delete/',
        organizer.Delete.as_view(),
        name='organizer_delete',
    ),
    path(
        'event/create/',
        event.Create.as_view(),
        name='event_create',
    ),
    path(
        'event/list/',
        event.List.as_view(),
        name='event_list',
    ),
    path(
        'event/<uuid:pk>/detail/',
        event.Detail.as_view(),
        name='event_detail',
    ),
    path(
        'event/<uuid:pk>/update/',
        event.Update.as_view(),
        name='event_update',
    ),
    path(
        'event/<uuid:pk>/delete/',
        event.Delete.as_view(),
        name='event_delete',
    ),
    path(
        'event/<uuid:event_uuid>/deck/create/',
        deck.Create.as_view(),
        name='deck_create',
    ),
    path(
        'event/<uuid:event_uuid>/deck/list/',
        deck.List.as_view(),
        name='deck_list',
    ),
    path(
        'event/<uuid:event_uuid>/deck/<uuid:pk>/detail/',
        deck.Detail.as_view(),
        name='deck_detail',
    ),
    path(
        'event/<uuid:event_uuid>/deck/<uuid:pk>/update/',
        deck.Update.as_view(),
        name='deck_update',
    ),
    path(
        'event/<uuid:event_uuid>/deck/<uuid:pk>/delete/',
        deck.Delete.as_view(),
        name='deck_delete',
    ),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('', include('django.contrib.auth.urls')),
]

urlpatterns += static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)

urlpatterns += static(
    settings.STATIC_URL,
    document_root=settings.STATIC_ROOT
)

app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
    <title>DeckManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="{% static 'bootstrap-5.1.0-dist/css/bootstrap.css' %}" />
    <link rel="stylesheet" href="{% static 'css/my.css' %}">
</head>

<body>
    <nav class="navbar navbar-dark bg-primary">
        <a class="navbar-brand" href="{% url 'app:index' %}">
            DeckManager
        </a>
    </nav>

    <ol class="breadcrumb">
        {% if request.user.is_authenticated %}
        <li class="breadcrumb-item"><a href="{% url 'app:event_create' %}">イベント新規作成</a></li>
        <li class="breadcrumb-item"><a href="{% url 'app:event_list' %}">マイイベント一覧</a></li>
        <li class="breadcrumb-item"><a href="{% url 'logout' %}">ログアウト</a></li>
        {% else %}
        <li class="breadcrumb-item"><a href="{% url 'app:organizer_create' %}">アカウント作成</a></li>
        <li class="breadcrumb-item"><a href="{% url 'login' %}">ログイン</a></li>
        {% endif %}
    </ol>

    {% if messages %}
    <div class="messages">
        {% for message in messages %}
        <p class="alert {{ message | bootstrap_message_classes }}">
            {{ message }}
        </p>
        {% endfor %}
    </div>
    {% endif %}

    {% block contents %}
    no contents
    {% endblock %}
</body>

</html>

app/templates/index.html
{% extends 'base.html' %}

{% block contents %}

index

{% endblock %}